server:
   port: 8080
   address: 0.0.0.0
springdoc:
  swagger-ui:
    enabled: true
    operaions-sorter: method

spring:
  application:
    name: chatting
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

token:
  secret-key: "SECRET"
  refresh-secret-key: "REFRESH_SECRET"
  token-time: 300
  refresh-token-time: 1440
