name: Deploy to EC2 via ECR & Kubernetes

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest"
          docker build -t $IMAGE_URI .
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Push Docker image to ECR
        run: |
          docker push $IMAGE_URI

      - name: Decode EC2 SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Connect to EC2 and update Kubernetes deployment
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=30 \
              -o ServerAliveCountMax=5 \
              -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          set -e

          echo "[INFO] Setting KUBECONFIG..."
          sudo mkdir -p /home/ubuntu/.kube
          sudo cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config
          sudo chown ubuntu:ubuntu /home/ubuntu/.kube/config
          export KUBECONFIG=/home/ubuntu/.kube/config

          echo "[INFO] Creating or updating ECR secret..."
          kubectl delete secret ecr-secret --ignore-not-found
          aws ecr get-login-password --region ap-northeast-2 | \
          kubectl create secret docker-registry ecr-secret \
            --docker-server=863518451270.dkr.ecr.ap-northeast-2.amazonaws.com \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password --region ap-northeast-2) \
            --docker-email=dummy@email.com

          echo "[INFO] Applying Kubernetes deployment..."
          cd ~/k8s
          kubectl apply -f chatting-deployment.yaml

          echo "[INFO] Deployment applied successfully."
          EOF
